version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.development
    volumes:
      - .:/app
    ports:
      - '27081:80'
    container_name: wxcloud_wxcloudrun-thinkphp-nginx
    labels:
      - wxPort=27082
      - hostPort=27081
      - wxcloud=wxcloudrun-thinkphp-nginx
      - role=container
    environment:
      # - MYSQL_USERNAME=cimer
      # - MYSQL_PASSWORD=cimer@@123@Z02O
      # - MYSQL_ADDRESS=172.16.2.10:3308
      - MYSQL_USERNAME=
      - MYSQL_PASSWORD=
      - MYSQL_ADDRESS=
networks:
  default:
    external:
      name: wxcb0
