version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.development
    volumes:
      - .:/app
    command: >-
      sh -c "mkdir -p /app/public/storage && chmod -R 777 /app/public/storage &&
      sh run.sh"
    ports:
      - '27081:80'
    container_name: wxcloud_wxcloudrun-thinkphp-nginx
    labels:
      - wxPort=27082
      - hostPort=27081
      - wxcloud=wxcloudrun-thinkphp-nginx
      - role=container
    environment:
      - MYSQL_USERNAME=
      - MYSQL_PASSWORD=
      - MYSQL_ADDRESS=
networks:
  default:
    external:
      name: wxcb0
